export {default as AllProductsPanel} from "./AllProductsPanel"
export {default as AddProductPanel} from "./AddProductPanel"
export {default as EditProductPanel} from "./EditProductPanel"
export {default as CategoriesPanel} from "./CategoriesPanel"
export {default as OrdersPanel} from "./OrdersPanel"
export {default as DiscountsPanel} from "./DiscountsPanel"
export {default as AnalyticsPanel} from "./AnalyticsPanel"
export {default as MembersPanel} from "./MembersPanel"